blank_issues_enabled: false
contact_links:
  - name: "\U0001F4D6 Project Documentation"
    url: https://github.com/Keshuin0/S.H.I.F.T/blob/main/README.md
    about: Read the project documentation before opening an issue
